// src/i18n/en.ts — English strings (source of truth for all locales)

import type { Translations } from "./types";

const en: Translations = {
  // Autopilot
  "autopilot.clickToStop": "Autopilot ON — click to stop",
  "autopilot.ariaCancel": "Autopilot active — click to cancel",

  // Audio
  "audio.mute": "Mute",
  "audio.unmute": "Unmute",

  // Toolbar
  "toolbar.restart": "Restart",
  "toolbar.screenshot": "Screenshot",
  "toolbar.showSolve": "Show how to solve this question",
  "toolbar.share": "Share",
  "toolbar.comments": "Comments",
  "toolbar.addComment": "+ Add Comment",

  // Level buttons
  "level.completePrev": "Complete Level {n} first",

  // Session report modal
  "report.shareReport": "Share Report",
  "report.creating": "Creating...",
  "report.nextLevel": "Next Level",
  "report.playAgain": "Play Again",
  "report.emailAria": "Email report",
  "report.sendTitle": "Send the report by email",
  "report.enterEmail": "Enter an email address",
  "report.emailPlaceholder": "parent@email.com",
  "report.levelComplete": "Level {level} Complete!",
  "report.subheading": "Monster Round Crushed!",
  "report.score": "Score",
  "report.accuracy": "Accuracy",
  "report.eggs": "Eggs",
  "report.sendSuccess": "Report sent to {email}",
  "report.sendFail": "Failed to send report.",

  // Game / RippleScreen
  "game.tapScreen": "Tap the screen! ({count}/{total})",
  "game.correct": "Correct!",
  "game.wrongAnswer": "Wrong! It was {answer}",
  "game.levelComplete": "Level Complete!",
  "game.entryPrompt": "How many ripples did you make?",
  "game.tryOnYourOwn": "Try on your own",
  "game.tapAnywhere": "Tap anywhere!",
  "game.next": "Next",
  "game.answerLabel": "Answer:",
  "game.roundLoad": "Load",
  "game.roundPack": "Pack",
  "game.roundShip": "Ship",
  "game.complete": "Complete",
  "game.nextRound": "Next",

  // Rotate prompt
  "rotate.heading": "Rotate your device",
  "rotate.subtext": "This game plays best in landscape mode",

  // Social
  "social.shareTitle": "Check out this maths game on Interactive Maths!",
  "social.commentsTitle": "DiscussIt comments",
  "social.youtubePrompt": "First time? Look at a video on how to play.",
  "social.youtubeDismiss": "Don't show again",
  "social.watchHowToPlay": "Watch how to play",
  "social.howToPlayVideo": "How to play video",
  "social.closeHowToPlayVideo": "Close how to play video",
  "social.howToPlayVideoPrompt": "How to play video prompt",
  "dev.recordDemoVideo": "Record demo video",

  // PDF report
  "pdf.title": "Pack It!",
  "pdf.sessionReport": "Session Report (Level {n})",
  "pdf.gameDescription": "Unitary Method and Unit Rates",
  "pdf.objectiveLabel": "Objective:",
  "pdf.objectiveText": "Pack items into equal groups, find the unit rate, and use it to solve the question.",
  "pdf.scoreLabel": "Score",
  "pdf.accuracyLabel": "Accuracy",
  "pdf.timeLabel": "Total Time",
  "pdf.questionLabel": "Q{n}",
  "pdf.correct": "CORRECT",
  "pdf.wrong": "WRONG",
  "pdf.givenAnswer": "Given Answer: {value}",
  "pdf.correctAnswer": "Correct answer: {value}",
  "pdf.rippleCount": "{count} ripple(s)",
  "pdf.durationSeconds": "{seconds}s",
  "pdf.durationMinutesSeconds": "{minutes}m {seconds}s",
  "pdf.encourage90": "Amazing work! You're a counting champion!",
  "pdf.encourage70": "Great job! You're getting really good at this!",
  "pdf.encourage50": "Nice effort! Keep practising and you'll be a pro!",
  "pdf.encourageBelow": "Good try! Every attempt makes you stronger!",
  "pdf.tip": "Tip: Try counting more carefully next time - take your time!",
  "pdf.footer": "Generated by SeeMaths - Pack It!",
  "pdf.footerUrl": "https://www.seemaths.com",

  // Email
  "email.subject": "{gameName} Report",
  "email.greeting": "Hi there,",
  "email.bodyIntro": "A player played {game} at SeeMaths at {time} on {date} for {duration}. They scored {score} and had an accuracy of {accuracy}.",
  "email.curriculumIntro": "This game is equivalent to {stageLabel} on topic {curriculumCode} - {curriculumDescription}.",
  "email.regards": "Regards,",
  "email.invalidEmail": "Enter a valid email address.",
  "email.missingPdf": "Report attachment is missing.",
  "email.notConfigured": "Email service is not configured.",
  "email.sendFailed": "Report email could not be sent.",

  // Curriculum
  "curriculum.stageEarlyStage1": "NSW Mathematics Stage 4",
  "curriculum.outcomeMae1wm": "Solves problems involving ratios and rates using the unitary method",

  // Language switcher
  "lang.label": "Language",
  "lang.en": "English",
  "lang.zh": "Chinese",
  "lang.es": "Spanish",
  "lang.ru": "Russian",
  "lang.hi": "Hindi",
  "lang.other": "Other...",
  "lang.translating": "Translating...",
  "lang.translateFail": "Translation failed.",
  "lang.promptTitle": "Translate to another language",
  "lang.promptPlaceholder": "e.g. French, Hindi, Arabic...",
  "lang.translate": "Translate",
  "lang.cancel": "Cancel",
};

export default en;
